-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("SUPER + Comma")
hl.bind("SUPER + Comma", hl.dsp.exec_cmd("dms ipc call settings toggle"), { description = "Settings: Toggle" })
hl.unbind("SUPER + Period")
hl.bind("SUPER + Period", hl.dsp.exec_cmd("sh -c \"dms ipc call spotlight toggleQuery \\\":e \\\"\""), { description = "Toggle Emoji" })
hl.unbind("SUPER + space")
hl.bind("SUPER + space", hl.dsp.exec_cmd("dms ipc call spotlight toggle"), { description = "Default Launcher: Toggle" })
hl.unbind("XF86AudioLowerVolume")
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("dms ipc call audio decrement 5"), { description = "Volume Down (5%)" })
hl.unbind("XF86AudioMute")
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("dms ipc call audio mute"), { description = "Volume Mute Toggle" })
hl.unbind("XF86AudioRaiseVolume")
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("dms ipc call audio increment 5"), { description = "Volume Up (5%)" })
hl.unbind("XF86Launch6")
hl.bind("XF86Launch6", hl.dsp.exec_cmd("dms ipc call mic mute"), { description = "Microphone Mute Toggle" })
hl.unbind("XF86MonBrightnessDown")
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("dms ipc call brightness decrement 5 \"\""), { description = "Brightness Down (5%)" })
hl.unbind("XF86MonBrightnessUp")
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("dms ipc call brightness increment 5 \"\""), { description = "Brightness Up (5%)" })
hl.unbind("SUPER + V")
hl.bind("SUPER + V", hl.dsp.exec_cmd("dms ipc call clipboard toggle"), { description = "Clipboard: Toggle" })
