config_version = 12

[bar.default]
background_opacity = 0.61999998614192009
border = "surface"
capsule = true
capsule_padding = 12.0
capsule_radius = 12
capsule_thickness = 0.7799999862909317
center = [ "active_window", "clock", "media" ]
end = [ "recorder", "group:g1", "group:g3", "cat_2", "notifications" ]
margin_ends = 0
panel_overlap = 0
radius_bottom_left = 11
radius_bottom_right = 11
radius_top_left = 0
radius_top_right = 0
scale = 0.90000000596046448
start = [ "session", "workspaces", "group:g2", "caffeine", "tray" ]
thickness = 38
widget_spacing = 10

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "ram", "sysmon" ]
    opacity = 1.0
    padding = 6.0
    radius = 80.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g2"
    members = [ "cpu", "temp" ]
    opacity = 1.0
    padding = 7.0
    radius = 12.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g3"
    members = [ "volume", "brightness", "battery" ]
    opacity = 1.0
    padding = 12.0
    radius = 16.0

[control_center.calendar]
show_events_card = false

[desktop_widgets]
schema_version = 2
widget_order = [ "desktop-widget-0000000000000001", "desktop-widget-0000000000000002" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 0.0
    box_width = 0.0
    cx = 112.5
    cy = 142.5
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 0.0
    box_width = 0.0
    cx = 1750.0
    cy = 908.0
    output = "eDP-1"
    rotation = 0.0
    type = "fancy_audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = false

[idle]
behavior_order = [ "idle-behavior", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 3

    [idle.behavior.idle-behavior]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[location]
auto_locate = true

[lockscreen]
blur_intensity = 0.29999999329447746
tint_intensity = 0.0
wallpaper = "/home/greed/Pictures/Wallpapers/walls/waterfall.png"

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000014",
    "lockscreen-widget-0000000000000015",
    "lockscreen-widget-0000000000000016",
    "lockscreen-widget-0000000000000018"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = false

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 512.0
    cx = 960.0
    cy = 716.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "outline"
        background_opacity = 1.0
        background_radius = 12.0
        center_password_text = true
        input_opacity = 1.0
        input_radius = 6.0
        layout = "compact"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = false
        show_media = false
        show_session_buttons = true
        show_unlock_hint = false
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000014]
    box_height = 80.0
    box_width = 368.0
    cx = 960.0
    cy = 468.0
    output = "eDP-1"
    rotation = 0.0
    type = "label"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000014.settings]
        background = false
        font_family = "0xProto Nerd Font"
        shadow = true
        title = "L O C K E D"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000015]
    box_height = 176.0
    box_width = 480.0
    cx = 960.0
    cy = 593.0
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000015.settings]
        background = false
        format = "{:%H:%M:%S}"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000016]
    box_height = 128.0
    box_width = 800.0
    cx = 960.0
    cy = 1020.0
    output = "eDP-1"
    rotation = 0.0
    type = "audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000016.settings]
        background = false
        bands = 80
        centered = false
        mirrored = false
        show_when_idle = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000018]
    box_height = 64.0
    box_width = 64.0
    cx = 32.0
    cy = 1048.0
    output = "eDP-1"
    rotation = 0.0
    type = "button"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000018.settings]
        background = false
        command = "systemctl poweroff"
        glyph = "power"
        variant = "default"

[notification]
border = false
offset_x = 8

[osd]
background_opacity = 0.99999997764825821
orientation = "vertical"
position_vertical = "center_right"

[plugin_settings."noctalia/screen_recorder"]
frame_rate = 165
video_source = "portal"

[plugins]
enabled = [ "noctalia/bongocat", "noctalia/screen_recorder" ]

[shell]
font_family = "Google Sans"
password_style = "random"
settings_show_advanced = true
telemetry_enabled = true

    [shell.animation]
    speed = 0.70000001043081284

    [shell.panel]
    launcher_placement = "attached"
    open_near_click_control_center = true
    open_near_click_session = true
    transparency_mode = "glass"

    [shell.screen_corners]
    enabled = true
    size = 16

    [shell.session]
    grid = true

    [shell.shadow]
    direction = "center"

[theme]
builtin = "Catppuccin"
community_palette = "Catppuccin Mocha Mauve"
mode = "dark"
source = "community"

[wallpaper]
directory = "/home/greed/Pictures/Wallpapers/walls"
transition_on_startup = true

    [wallpaper.default]
    path = "/home/greed/Pictures/Wallpapers/walls/illustration-anime-city_catppuccin-mocha.jpg"

    [wallpaper.last]
    path = "/home/greed/Pictures/Wallpapers/walls/illustration-anime-city_catppuccin-mocha.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/greed/Pictures/Wallpapers/walls/illustration-anime-city_catppuccin-mocha.jpg"

[widget.active_window]
capsule = true
capsule_radius = 13
icon_size = 21
max_length = 256
title_scroll = "on_hover"

[widget.brightness]
show_label = false

[widget.cat]
type = "noctalia/bongocat:cat"

[widget.cat_2]
input_devices = [ "/dev/input/event5" ]
scale = 1.95
type = "noctalia/bongocat:cat"

[widget.clock]
anchor = true
format = "{:%H:%M:%S • %a, %b %d}"

[widget.control-center]
capsule = true

[widget.media]
hide_when_no_media = true

[widget.notifications]
capsule = true
capsule_padding = 8.0

[widget.ram]
display = "text"
font_weight = 700
stat = "ram_pct"
visualization = "none"

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.session]
capsule = true

[widget.swap]
stat = "swap_pct"

[widget.sysmon]
stat = "swap_pct"

[widget.tray]
drawer = true

[widget.workspaces]
active_pill_size = 2.3999999999999999
focused_output_only = true
hide_when_empty = true
max_label_chars = 2