add_newline = false


format = """
[╭](bold overlay1)\
$python\
$directory\
$git_branch\
$git_status\
$kubernetes \
$cmd_duration \
\n$character"""


palette = 'catppuccin_mocha'
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"


[palettes.gruvbox]
color_fg0 = '#ebdbb2'   # text foreground
color_bg0 = '#3C4841'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_red = '#cc241d'
color_yellow = '#d79921'


[character]
format = """
[╰─$symbol](fg:overlay1) """
success_symbol = '[](fg:bold green)'
error_symbol = '[](fg:bold red)'


[fill]
symbol = '-'
style = 'fg:245'


[directory]
# style = "fg:color_fg0 bg:color_bg0"
format = '[](bold fg:surface1)[$path](bold bg:surface1 fg:pink)(fg:bold teal)[](bold fg:surface1)'
# format = 'in [$path](fg:bold teal)'
truncation_length = 3
truncation_symbol = "·/"
fish_style_pwd_dir_length = 1

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[kubernetes]
disabled = false
style = "fg:color_yellow"
format = '( | [$context]($style)( in [$namespace]($style)))'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '| $time'

[git_branch]
format = " ~ [](bold fg:surface1)[in [$symbol$branch](bold bg:surface1 fg:rosewater) with ](bold bg:surface1 fg:text)"
symbol = "[ ](bold bg:surface1 fg:green)"

[git_status]
format = "[$all_status$ahead_behind](fg:text bg:surface1)[](fg:surface1)"
conflicted = "="
ahead = "[⇡${count} ](fg:bold green bg:surface1)"
behind = "⇣${count}(fg:bold teal bg:surface1) "
diverged = "[⇕⇡${ahead_count} ⇣${behind_count} ](fg:bold teal bg:surface1)"
up_to_date = "[󰄸 ](fg:bold green bg:surface1)"
untracked = "[?${count} ](fg:bold maroon bg:surface1)"
stashed = "[󰏖  ](fg:bold green bg:surface1)"
modified = "[~${count} ](fg:bold yellow bg:surface1)"
staged = "[+${count} ](fg:bold green bg:surface1)"
renamed = "[»${count} ](fg:bold peach bg:surface1)"
# deleted = "[ ${count} ](bold red)"
deleted = "[-${count} ](fg:bold red bg:surface1)"

[git_commit]
format = "[\\($hash\\)]($style) [\\($tag\\)]($style)"
style = "green"

[git_state]
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
style = "yellow"
format = '\([$state( $progress_current/$progress_total)]($style)\) '

[cmd_duration]
min_time = 10
# format = '| 󰪢 [$duration](bold purple)'
format = '~ [](bold fg:surface1)[󰪢 $duration](bold bg:surface1 fg:mauve)[](bold fg:surface1)'
show_milliseconds = true

# [python]
# symbol = " "
# format = '[]($style)[(\($virtualenv\))](bg:#161821 fg:#BBC3DF)[ ]($style)'
# style = "bg:none fg:#161821"

[python]
symbol = " "
format = '[(\($virtualenv\) | )]($style)'


