# Layer rules (see docs/user/rules.md#layer-rules) ---------------------------

[[layer_rule]]
match.namespace = "^noctalia-(bar-[^\"]+|notification|dock|panel|attached-panel|osd)$"
blur = true
blur_ignore_alpha = 0.5
blur_optimized = false
