#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 
# bspc monitor -d                󰓇  󰙯

bspc config border_width        2
bspc config window_gap					9
bspc config top_padding         0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a firefox desktop='^1' follow = on
bspc rule -a org.gnome.Nautilus desktop='^6' follow = on
bspc rule -a pcmanfm desktop='^6'
bspc rule -a zathura desktop='^7' follow = on 
bspc rule -a zathura state=tile 
bspc rule -a evince desktop='^7'
bspc rule -a Spotify desktop='^8'
bspc rule -a discord desktop='^9'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

wmname BSPWM
spotify &
volctl &
discord &
picom --config ~/.config/picom/picom.conf &
cbatticon &
nitrogen --restore &
# exec ~/.config/chadwm/scripts/bar.sh &
polybar bar &
kdeconnect-app &
nm-applet &
xpad &
