#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d  	 		 				阮 ﭮ

bspc config border_width        2
bspc config window_gap					3          

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a firefox desktop='^1'
bspc rule -a thunar desktop='^6'
bspc rule -a spotify desktop='^8' 
bspc rule -a discord desktop='^9'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

wmname BSPWM
volctl &
discord &
picom --config ~/.config/picom/picom.conf &
cbatticon &
nitrogen --restore &
polybar bar &
nm-applet &
