#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#----------------> Monitor Rules <----------------

bspc monitor -d 1 2 3 4 5 6 7   
#          ﭮ
# bspc monitor -d                󰓇  󰙯


#----------------> BSPWM Rules <----------------

bspc config border_width        1
bspc config window_gap					10
bspc config top_padding         60

bspc config focused_border_color "#7aa2f7"
bspc config normal_border_color "#a9b1d6"
bspc config active_border_color "#c0caf5"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false


#----------------> Application Rules <----------------

bspc rule -a firefox desktop='^1' follow = on
bspc rule -a vlc desktop='^4' follow = on
bspc rule -a sioyek desktop='^3' follow = on
bspc rule -a Thunar desktop='^4' follow = on
bspc rule -a kdeconnect-app desktop='^5' follow = on
bspc rule -a Spotify desktop='^6'
bspc rule -a discord desktop='^7'
bspc rule -a telegram-desktop desktop='^7'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# bspc rule -a pcmanfm desktop='^6' follow = on
# bspc rule -a zathura desktop='^7' follow = on state=tile 
# bspc rule -a evince desktop='^7'

bspc rule -a Xfce4-panel state=floating border=off
bspc rule -a xfce4-popup-whiskermenu state=floating border=off
bspc rule -a Whisker\ Menu state=floating border=off
bspc rule -a Findex state=floating border=off
bspc rule -a Wrapper-2.0 state=floating border=off focus=on
# bspc rule -a Xfce4-appfinder state=floating border=off
# bspc rule -a xfce4-panel state=floating border=off focus=on
# bspc rule -a findex border=off

#----------------> Startup <----------------
wmname BSPWM
lxappearance
killall lxappearance
# nm-applet &
# nitrogen --restore &
# spotify &
# volctl &
# discord &
# picom --config ~/.config/picom/picom.conf &
# kdeconnect-app &
# cbatticon --icon-type notification &
# exec ~/.config/chadwm/scripts/bar.sh &
# polybar bar &
# ~/.config/polybar/launch.sh --grayblocks
# clipmenud &
