[colors]
background = "#313244F0"
text_primary = "#cdd6f4FF"
text_muted = "#a3b4ebFF"
accent_primary = "#cba6f7FF"
accent_secondary = "#fab387FF"
warning = "#94e2d5FF"
error = "#f38ba8FF"

[appearance]
border_focused = "#cba6f7FF"
border_unfocused = "#313244FF"
scratchpad_border_focused = "#94e2d5FF"
scratchpad_border_unfocused = "#23a08bFF"
outer_border_color = "#1e1e2eFF"
insert_hint_color = "#94e2d580"
backdrop_color = "#313244FF"

[overview]
background_tint = "#1e1e2e88"
