[colors]
background = "#313244FF"
text_primary = "#cdd6f4FF"
text_muted = "#a3b4ebFF"
accent_primary = "#cba6f7FF"
accent_secondary = "#fab387FF"
warning = "#94e2d5FF"
error = "#f38ba8FF"
insert_hint = "#94e2d580"
backdrop = "#313244FF"

[colors.border]
focused = "#cba6f7FF"
unfocused = "#313244FF"
scratchpad_focused = "#94e2d5FF"
scratchpad_unfocused = "#23a08bFF"
outer = "#1e1e2eFF"

[colors.overview]
background_tint = "#1e1e2e88"
badge = "#cba6f7FF"
workspace_background = "#1e1e2eFF"
